- Inserted a delay in debian initscript

diff --git a/debian/plptools.init b/debian/plptools.init
--- a/debian/plptools.init
+++ b/debian/plptools.init
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-# start or stop the plptools daemon
+# start or stop the plptools daemons
 #
 
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
@@ -24,21 +24,22 @@ case "$1" in
 		echo -n "Starting $DESC ($DAEMON1): "
 		start-stop-daemon --start --quiet \
 			--exec $DAEMON1 -- $NCPD_ARGS && \
-				echo -n "done" || echo -n "already running"
+				echo -n "done" || echo -n "failed"
 		echo "."
+		sleep 1
 	fi
 	if test "$START_PLPNFSD" = "yes" ; then
 		echo -n "Starting $DESC ($DAEMON2): "
 		start-stop-daemon --start --quiet \
 			--exec $DAEMON2 -- $PLPNFSD_ARGS && \
-			echo -n "done" || echo -n "already running"
+			echo -n "done" || echo -n "failed"
 		echo "."
 	fi
 	if test "$START_PLPPRINTD" = "yes" ; then
 		echo -n "Starting $DESC ($DAEMON3): "
 		start-stop-daemon --start --quiet \
 			--exec $DAEMON3 -- $PLPPRINTD_ARGS && \
-			echo -n "done" || echo -n "already running"
+			echo -n "done" || echo -n "failed"
 		echo "."
 	fi
 	;;
